[github]

# Information for securely interacting with GitHub. These are
# found/generated under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = ""

# A GitHub oauth application for this instance of homu:
app_client_id = ""
app_client_secret = ""

[web]

# The port homu listens on
port = 54856

[per-repo.github]
# arbitrary secret (e.g. openssl rand -hex 20)
secret = ""


## Use travis for running tests
# [per-repo.travis]
# token = ""
